const products = [
  {
    name: "Makeup ForEver Ultra HD",
    url: "makeup-forever-ultra-hd",
    category: "Lip Gloss",
    price: "₹ 250",
    image: "lip-gloss.jpg",
    shades: [
      "rgb(255 237 213)",
      "rgb(254 215 170",
      "rgb(253 186 116)",
      "rgb(251 146 60)",
    ],
    description: [
      "Introducing our fabulous lipgloss - the perfect finishing touch to your makeup look!",
      "Our lipgloss is available in a range of stunning shades, each designed to add a touch of glamour to your lips. Our formula is enriched with nourishing ingredients like jojoba oil and vitamin E, providing a luscious shine and hydrating your lips at the same time.",
      "Our lipgloss is lightweight and non-sticky, ensuring a comfortable wear throughout the day. It's perfect for wearing on its own for a subtle hint of color or layering over your favorite lipstick for a high-shine finish.",
      "The formula of our lipgloss is designed to be long-lasting, so you can wear it all day or all night without worrying about touch-ups. Our lipgloss is also smudge-proof, so you can enjoy your day without worrying about your lip color fading or transferring.",
      "The packaging of our lipgloss is stylish and compact, making it easy to take with you on the go. The sleek design fits easily in your purse or pocket, so you can touch up your lip color whenever and wherever you need to.",
      "Invest in our lipgloss today and add a touch of sophistication to your makeup routine. Our formula is high-quality and luxurious, providing you with a bold and beautiful look that lasts all day.",
    ],
  },
  {
    name: "Chaoba Professional",
    url: "chaoba-professional",
    category: "Eyeshadow",
    price: "₹ 150",
    image: "eyeshadow-product.jpg",
    shades: [
      "rgb(241,207,207)",
      "rgb(228,177,177)",
      "rgb(215,145,145)",
      "rgb(178,110,110)",
      "rgb(109,46,46)",
    ],
    description: [
      "Introducing our stunning eyeshadow palette - the perfect addition to your makeup collection!",
      "Our eyeshadow palette features a versatile range of 12 pigmented shades, perfect for creating endless eye-catching looks. From bold and dramatic to soft and subtle, our palette has something for every occasion. ",
      "The shades in our palette have been carefully selected to complement a range of skin tones and eye colors, allowing you to experiment with different combinations to create your own unique look. Whether you're after a natural daytime look or a glamorous evening look, our eyeshadow palette has got you covered.",
      "The formula of our eyeshadows is silky smooth and blends effortlessly, making it easy to create a flawless finish. The long-lasting formula ensures that your eye makeup stays put all day and night, without creasing or fading.<br/>Our palette comes in a sleek and compact design, making it perfect for on-the-go touch-ups or travel. It also comes with a mirror and applicator brush for added convenience.",
      "Invest in our eyeshadow palette today and take your eye makeup game to the next level!",
    ],
  },
  {
    name: "Huda Beauty",
    url: "huda-beauty",
    category: "Foundation Stick",
    price: "₹ 450",
    image: "huda-beauty.jpg",
    shades: [
      "rgb(204,165,126)",
      "rgb(216,181,154)",
      "rgb(229,200,178)",
      "rgb(235,219,206)",
      "rgb(248,238,230)",
    ],
    description: [
      "Introducing our revolutionary foundation stick - the perfect addition to your makeup collection!",
      "Our foundation stick is available in a range of shades, each designed to match a variety of skin tones and undertones. Our formula is rich and creamy, gliding effortlessly onto your skin to create a flawless and natural-looking finish.",
      "Our foundation stick is versatile and easy to use, making it perfect for those who are always on-the-go. The stick formula is easy to apply, allowing you to target specific areas of your face for precise coverage. The blendable formula allows you to build up coverage from light to full, providing a customizable finish that suits your needs.",
      "Our foundation stick is formulated with high-quality ingredients, ensuring a long-lasting wear throughout the day. The formula is also designed to be non-greasy and lightweight, allowing your skin to breathe while providing coverage.",
      "The packaging of our foundation stick is sleek and convenient, making it perfect for travel or touch-ups on the go. The compact design fits easily in your purse or makeup bag, allowing you to take it with you wherever you go.",
      "Invest in our foundation stick today and experience the perfect coverage for a natural and radiant look. Our formula is high-quality and luxurious, providing you with a flawless finish that lasts all day.",
    ],
  },
  {
    name: "Mars Matte Lipcolor",
    url: "mars-matte-lipstick",
    category: "Lipstick",
    price: "₹ 250",
    image: "lipstick-product.jpg",
    shades: [
      "rgb(220, 55, 83)",
      "rgb(229, 109, 126)",
      "rgb(139, 22, 14)",
      "rgb184, 105, 106)",
      "rgb(204, 172, 158)",
    ],
    description: [
      "Introducing our exquisite range of lipsticks - the perfect addition to your makeup collection!",
      "Our lipsticks are available in a range of shades and finishes, from bold and bright to subtle and understated. Our carefully curated collection features hues that complement a wide range of skin tones and personalities, so you're sure to find a shade that speaks to you.",
      "Our lipstick formula is luxurious and creamy, gliding effortlessly onto your lips to create a bold and beautiful look. Infused with nourishing ingredients like vitamin E and avocado oil, our lipstick will keep your lips feeling soft and moisturized, all day long.",
      "Our lipsticks have a long-lasting formula, ensuring that your lip color stays put for hours without smudging or fading. You can rest assured that your lipstick will stay in place, even after enjoying a meal or sipping a drink.",
      "The packaging of our lipsticks is elegant and sleek, making them the perfect addition to your vanity or handbag. The design of our lipstick tube is not only aesthetically pleasing, but it is also functional, making it easy to apply your lipstick with precision.",
      "Invest in our range of lipsticks today and elevate your look with our high-quality and glamorous shades. Our lipsticks are the perfect accessory for any occasion, whether you're headed to work or out on the town with friends.",
    ],
  },
  {
    name: "Makeup ForEver Ultra HD",
    url: "makeup-forever-ultra-hd",
    category: "Lip Gloss",
    price: "₹ 250",
    image: "lip-gloss.jpg",
    shades: [
      "rgb(255 237 213)",
      "rgb(254 215 170",
      "rgb(253 186 116)",
      "rgb(251 146 60)",
    ],
    description: [
      "Introducing our fabulous lipgloss - the perfect finishing touch to your makeup look!",
      "Our lipgloss is available in a range of stunning shades, each designed to add a touch of glamour to your lips. Our formula is enriched with nourishing ingredients like jojoba oil and vitamin E, providing a luscious shine and hydrating your lips at the same time.",
      "Our lipgloss is lightweight and non-sticky, ensuring a comfortable wear throughout the day. It's perfect for wearing on its own for a subtle hint of color or layering over your favorite lipstick for a high-shine finish.",
      "The formula of our lipgloss is designed to be long-lasting, so you can wear it all day or all night without worrying about touch-ups. Our lipgloss is also smudge-proof, so you can enjoy your day without worrying about your lip color fading or transferring.",
      "The packaging of our lipgloss is stylish and compact, making it easy to take with you on the go. The sleek design fits easily in your purse or pocket, so you can touch up your lip color whenever and wherever you need to.",
      "Invest in our lipgloss today and add a touch of sophistication to your makeup routine. Our formula is high-quality and luxurious, providing you with a bold and beautiful look that lasts all day.",
    ],
  },
  {
    name: "Chaoba Professional",
    url: "chaoba-professional",
    category: "Eyeshadow",
    price: "₹ 150",
    image: "eyeshadow-product.jpg",
    shades: [
      "rgb(241,207,207)",
      "rgb(228,177,177)",
      "rgb(215,145,145)",
      "rgb(178,110,110)",
      "rgb(109,46,46)",
    ],
    description: [
      "Introducing our stunning eyeshadow palette - the perfect addition to your makeup collection!",
      "Our eyeshadow palette features a versatile range of 12 pigmented shades, perfect for creating endless eye-catching looks. From bold and dramatic to soft and subtle, our palette has something for every occasion. ",
      "The shades in our palette have been carefully selected to complement a range of skin tones and eye colors, allowing you to experiment with different combinations to create your own unique look. Whether you're after a natural daytime look or a glamorous evening look, our eyeshadow palette has got you covered.",
      "The formula of our eyeshadows is silky smooth and blends effortlessly, making it easy to create a flawless finish. The long-lasting formula ensures that your eye makeup stays put all day and night, without creasing or fading.<br/>Our palette comes in a sleek and compact design, making it perfect for on-the-go touch-ups or travel. It also comes with a mirror and applicator brush for added convenience.",
      "Invest in our eyeshadow palette today and take your eye makeup game to the next level!",
    ],
  },
  {
    name: "Huda Beauty",
    url: "huda-beauty",
    category: "Foundation Stick",
    price: "₹ 450",
    image: "huda-beauty.jpg",
    shades: [
      "rgb(204,165,126)",
      "rgb(216,181,154)",
      "rgb(229,200,178)",
      "rgb(235,219,206)",
      "rgb(248,238,230)",
    ],
    description: [
      "Introducing our revolutionary foundation stick - the perfect addition to your makeup collection!",
      "Our foundation stick is available in a range of shades, each designed to match a variety of skin tones and undertones. Our formula is rich and creamy, gliding effortlessly onto your skin to create a flawless and natural-looking finish.",
      "Our foundation stick is versatile and easy to use, making it perfect for those who are always on-the-go. The stick formula is easy to apply, allowing you to target specific areas of your face for precise coverage. The blendable formula allows you to build up coverage from light to full, providing a customizable finish that suits your needs.",
      "Our foundation stick is formulated with high-quality ingredients, ensuring a long-lasting wear throughout the day. The formula is also designed to be non-greasy and lightweight, allowing your skin to breathe while providing coverage.",
      "The packaging of our foundation stick is sleek and convenient, making it perfect for travel or touch-ups on the go. The compact design fits easily in your purse or makeup bag, allowing you to take it with you wherever you go.",
      "Invest in our foundation stick today and experience the perfect coverage for a natural and radiant look. Our formula is high-quality and luxurious, providing you with a flawless finish that lasts all day.",
    ],
  },
  {
    name: "Mars Matte Lipcolor",
    url: "mars-matte-lipstick",
    category: "Lipstick",
    price: "₹ 250",
    image: "lipstick-product.jpg",
    shades: [
      "rgb(220, 55, 83)",
      "rgb(229, 109, 126)",
      "rgb(139, 22, 14)",
      "rgb184, 105, 106)",
      "rgb(204, 172, 158)",
    ],
    description: [
      "Introducing our exquisite range of lipsticks - the perfect addition to your makeup collection!",
      "Our lipsticks are available in a range of shades and finishes, from bold and bright to subtle and understated. Our carefully curated collection features hues that complement a wide range of skin tones and personalities, so you're sure to find a shade that speaks to you.",
      "Our lipstick formula is luxurious and creamy, gliding effortlessly onto your lips to create a bold and beautiful look. Infused with nourishing ingredients like vitamin E and avocado oil, our lipstick will keep your lips feeling soft and moisturized, all day long.",
      "Our lipsticks have a long-lasting formula, ensuring that your lip color stays put for hours without smudging or fading. You can rest assured that your lipstick will stay in place, even after enjoying a meal or sipping a drink.",
      "The packaging of our lipsticks is elegant and sleek, making them the perfect addition to your vanity or handbag. The design of our lipstick tube is not only aesthetically pleasing, but it is also functional, making it easy to apply your lipstick with precision.",
      "Invest in our range of lipsticks today and elevate your look with our high-quality and glamorous shades. Our lipsticks are the perfect accessory for any occasion, whether you're headed to work or out on the town with friends.",
    ],
  },
  {
    name: "Makeup ForEver Ultra HD",
    url: "makeup-forever-ultra-hd",
    category: "Lip Gloss",
    price: "₹ 250",
    image: "lip-gloss.jpg",
    shades: [
      "rgb(255 237 213)",
      "rgb(254 215 170",
      "rgb(253 186 116)",
      "rgb(251 146 60)",
    ],
    description: [
      "Introducing our fabulous lipgloss - the perfect finishing touch to your makeup look!",
      "Our lipgloss is available in a range of stunning shades, each designed to add a touch of glamour to your lips. Our formula is enriched with nourishing ingredients like jojoba oil and vitamin E, providing a luscious shine and hydrating your lips at the same time.",
      "Our lipgloss is lightweight and non-sticky, ensuring a comfortable wear throughout the day. It's perfect for wearing on its own for a subtle hint of color or layering over your favorite lipstick for a high-shine finish.",
      "The formula of our lipgloss is designed to be long-lasting, so you can wear it all day or all night without worrying about touch-ups. Our lipgloss is also smudge-proof, so you can enjoy your day without worrying about your lip color fading or transferring.",
      "The packaging of our lipgloss is stylish and compact, making it easy to take with you on the go. The sleek design fits easily in your purse or pocket, so you can touch up your lip color whenever and wherever you need to.",
      "Invest in our lipgloss today and add a touch of sophistication to your makeup routine. Our formula is high-quality and luxurious, providing you with a bold and beautiful look that lasts all day.",
    ],
  },
  {
    name: "Chaoba Professional",
    url: "chaoba-professional",
    category: "Eyeshadow",
    price: "₹ 150",
    image: "eyeshadow-product.jpg",
    shades: [
      "rgb(241,207,207)",
      "rgb(228,177,177)",
      "rgb(215,145,145)",
      "rgb(178,110,110)",
      "rgb(109,46,46)",
    ],
    description: [
      "Introducing our stunning eyeshadow palette - the perfect addition to your makeup collection!",
      "Our eyeshadow palette features a versatile range of 12 pigmented shades, perfect for creating endless eye-catching looks. From bold and dramatic to soft and subtle, our palette has something for every occasion. ",
      "The shades in our palette have been carefully selected to complement a range of skin tones and eye colors, allowing you to experiment with different combinations to create your own unique look. Whether you're after a natural daytime look or a glamorous evening look, our eyeshadow palette has got you covered.",
      "The formula of our eyeshadows is silky smooth and blends effortlessly, making it easy to create a flawless finish. The long-lasting formula ensures that your eye makeup stays put all day and night, without creasing or fading.<br/>Our palette comes in a sleek and compact design, making it perfect for on-the-go touch-ups or travel. It also comes with a mirror and applicator brush for added convenience.",
      "Invest in our eyeshadow palette today and take your eye makeup game to the next level!",
    ],
  },
  {
    name: "Huda Beauty",
    url: "huda-beauty",
    category: "Foundation Stick",
    price: "₹ 450",
    image: "huda-beauty.jpg",
    shades: [
      "rgb(204,165,126)",
      "rgb(216,181,154)",
      "rgb(229,200,178)",
      "rgb(235,219,206)",
      "rgb(248,238,230)",
    ],
    description: [
      "Introducing our revolutionary foundation stick - the perfect addition to your makeup collection!",
      "Our foundation stick is available in a range of shades, each designed to match a variety of skin tones and undertones. Our formula is rich and creamy, gliding effortlessly onto your skin to create a flawless and natural-looking finish.",
      "Our foundation stick is versatile and easy to use, making it perfect for those who are always on-the-go. The stick formula is easy to apply, allowing you to target specific areas of your face for precise coverage. The blendable formula allows you to build up coverage from light to full, providing a customizable finish that suits your needs.",
      "Our foundation stick is formulated with high-quality ingredients, ensuring a long-lasting wear throughout the day. The formula is also designed to be non-greasy and lightweight, allowing your skin to breathe while providing coverage.",
      "The packaging of our foundation stick is sleek and convenient, making it perfect for travel or touch-ups on the go. The compact design fits easily in your purse or makeup bag, allowing you to take it with you wherever you go.",
      "Invest in our foundation stick today and experience the perfect coverage for a natural and radiant look. Our formula is high-quality and luxurious, providing you with a flawless finish that lasts all day.",
    ],
  },
  {
    name: "Mars Matte Lipcolor",
    url: "mars-matte-lipstick",
    category: "Lipstick",
    price: "₹ 250",
    image: "lipstick-product.jpg",
    shades: [
      "rgb(220, 55, 83)",
      "rgb(229, 109, 126)",
      "rgb(139, 22, 14)",
      "rgb184, 105, 106)",
      "rgb(204, 172, 158)",
    ],
    description: [
      "Introducing our exquisite range of lipsticks - the perfect addition to your makeup collection!",
      "Our lipsticks are available in a range of shades and finishes, from bold and bright to subtle and understated. Our carefully curated collection features hues that complement a wide range of skin tones and personalities, so you're sure to find a shade that speaks to you.",
      "Our lipstick formula is luxurious and creamy, gliding effortlessly onto your lips to create a bold and beautiful look. Infused with nourishing ingredients like vitamin E and avocado oil, our lipstick will keep your lips feeling soft and moisturized, all day long.",
      "Our lipsticks have a long-lasting formula, ensuring that your lip color stays put for hours without smudging or fading. You can rest assured that your lipstick will stay in place, even after enjoying a meal or sipping a drink.",
      "The packaging of our lipsticks is elegant and sleek, making them the perfect addition to your vanity or handbag. The design of our lipstick tube is not only aesthetically pleasing, but it is also functional, making it easy to apply your lipstick with precision.",
      "Invest in our range of lipsticks today and elevate your look with our high-quality and glamorous shades. Our lipsticks are the perfect accessory for any occasion, whether you're headed to work or out on the town with friends.",
    ],
  },
  {
    name: "Makeup ForEver Ultra HD",
    url: "makeup-forever-ultra-hd",
    category: "Lip Gloss",
    price: "₹ 250",
    image: "lip-gloss.jpg",
    shades: [
      "rgb(255 237 213)",
      "rgb(254 215 170",
      "rgb(253 186 116)",
      "rgb(251 146 60)",
    ],
    description: [
      "Introducing our fabulous lipgloss - the perfect finishing touch to your makeup look!",
      "Our lipgloss is available in a range of stunning shades, each designed to add a touch of glamour to your lips. Our formula is enriched with nourishing ingredients like jojoba oil and vitamin E, providing a luscious shine and hydrating your lips at the same time.",
      "Our lipgloss is lightweight and non-sticky, ensuring a comfortable wear throughout the day. It's perfect for wearing on its own for a subtle hint of color or layering over your favorite lipstick for a high-shine finish.",
      "The formula of our lipgloss is designed to be long-lasting, so you can wear it all day or all night without worrying about touch-ups. Our lipgloss is also smudge-proof, so you can enjoy your day without worrying about your lip color fading or transferring.",
      "The packaging of our lipgloss is stylish and compact, making it easy to take with you on the go. The sleek design fits easily in your purse or pocket, so you can touch up your lip color whenever and wherever you need to.",
      "Invest in our lipgloss today and add a touch of sophistication to your makeup routine. Our formula is high-quality and luxurious, providing you with a bold and beautiful look that lasts all day.",
    ],
  },
  {
    name: "Chaoba Professional",
    url: "chaoba-professional",
    category: "Eyeshadow",
    price: "₹ 150",
    image: "eyeshadow-product.jpg",
    shades: [
      "rgb(241,207,207)",
      "rgb(228,177,177)",
      "rgb(215,145,145)",
      "rgb(178,110,110)",
      "rgb(109,46,46)",
    ],
    description: [
      "Introducing our stunning eyeshadow palette - the perfect addition to your makeup collection!",
      "Our eyeshadow palette features a versatile range of 12 pigmented shades, perfect for creating endless eye-catching looks. From bold and dramatic to soft and subtle, our palette has something for every occasion. ",
      "The shades in our palette have been carefully selected to complement a range of skin tones and eye colors, allowing you to experiment with different combinations to create your own unique look. Whether you're after a natural daytime look or a glamorous evening look, our eyeshadow palette has got you covered.",
      "The formula of our eyeshadows is silky smooth and blends effortlessly, making it easy to create a flawless finish. The long-lasting formula ensures that your eye makeup stays put all day and night, without creasing or fading.<br/>Our palette comes in a sleek and compact design, making it perfect for on-the-go touch-ups or travel. It also comes with a mirror and applicator brush for added convenience.",
      "Invest in our eyeshadow palette today and take your eye makeup game to the next level!",
    ],
  },
  {
    name: "Huda Beauty",
    url: "huda-beauty",
    category: "Foundation Stick",
    price: "₹ 450",
    image: "huda-beauty.jpg",
    shades: [
      "rgb(204,165,126)",
      "rgb(216,181,154)",
      "rgb(229,200,178)",
      "rgb(235,219,206)",
      "rgb(248,238,230)",
    ],
    description: [
      "Introducing our revolutionary foundation stick - the perfect addition to your makeup collection!",
      "Our foundation stick is available in a range of shades, each designed to match a variety of skin tones and undertones. Our formula is rich and creamy, gliding effortlessly onto your skin to create a flawless and natural-looking finish.",
      "Our foundation stick is versatile and easy to use, making it perfect for those who are always on-the-go. The stick formula is easy to apply, allowing you to target specific areas of your face for precise coverage. The blendable formula allows you to build up coverage from light to full, providing a customizable finish that suits your needs.",
      "Our foundation stick is formulated with high-quality ingredients, ensuring a long-lasting wear throughout the day. The formula is also designed to be non-greasy and lightweight, allowing your skin to breathe while providing coverage.",
      "The packaging of our foundation stick is sleek and convenient, making it perfect for travel or touch-ups on the go. The compact design fits easily in your purse or makeup bag, allowing you to take it with you wherever you go.",
      "Invest in our foundation stick today and experience the perfect coverage for a natural and radiant look. Our formula is high-quality and luxurious, providing you with a flawless finish that lasts all day.",
    ],
  },
  {
    name: "Mars Matte Lipcolor",
    url: "mars-matte-lipstick",
    category: "Lipstick",
    price: "₹ 250",
    image: "lipstick-product.jpg",
    shades: [
      "rgb(220, 55, 83)",
      "rgb(229, 109, 126)",
      "rgb(139, 22, 14)",
      "rgb184, 105, 106)",
      "rgb(204, 172, 158)",
    ],
    description: [
      "Introducing our exquisite range of lipsticks - the perfect addition to your makeup collection!",
      "Our lipsticks are available in a range of shades and finishes, from bold and bright to subtle and understated. Our carefully curated collection features hues that complement a wide range of skin tones and personalities, so you're sure to find a shade that speaks to you.",
      "Our lipstick formula is luxurious and creamy, gliding effortlessly onto your lips to create a bold and beautiful look. Infused with nourishing ingredients like vitamin E and avocado oil, our lipstick will keep your lips feeling soft and moisturized, all day long.",
      "Our lipsticks have a long-lasting formula, ensuring that your lip color stays put for hours without smudging or fading. You can rest assured that your lipstick will stay in place, even after enjoying a meal or sipping a drink.",
      "The packaging of our lipsticks is elegant and sleek, making them the perfect addition to your vanity or handbag. The design of our lipstick tube is not only aesthetically pleasing, but it is also functional, making it easy to apply your lipstick with precision.",
      "Invest in our range of lipsticks today and elevate your look with our high-quality and glamorous shades. Our lipsticks are the perfect accessory for any occasion, whether you're headed to work or out on the town with friends.",
    ],
  },
];

export default products;
